### Login de Usuario
POST http://localhost:8080/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmb3JvIGh1YiIsInN1YiI6ImFkcmlhbmFAZW1haWwuY29tIiwiaWQiOjEsImV4cCI6MTc3MTcxODE0OH0.zX9pF0mSo6JcoozK7v9lwGRoYj1DTlXbFXWYq6VliWs

Content-Type: application/json

{
  "login": "adriana@email.com",
  "clave": "123456"
}

### 1. Registrar un nuevo tópico (CREATE)
POST http://localhost:8080/topicos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmb3JvIGh1YiIsInN1YiI6ImFkcmlhbmFAZW1haWwuY29tIiwiaWQiOjEsImV4cCI6MTc3MTcxODE0OH0.zX9pF0mSo6JcoozK7v9lwGRoYj1DTlXbFXWYq6VliWs

Content-Type: application/json

{
  "titulo": "Prueba número 2",
  "mensaje": "Comprobando que lo hice bien",
  "autor": "Adriana",
  "curso": "Spring Boot 3"
}

### 2. Listar todos los tópicos (READ ALL)
GET http://localhost:8080/topicos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmb3JvIGh1YiIsInN1YiI6ImFkcmlhbmFAZW1haWwuY29tIiwiaWQiOjEsImV4cCI6MTc3MTcxODE0OH0.zX9pF0mSo6JcoozK7v9lwGRoYj1DTlXbFXWYq6VliWs

### 3. Detallar un tópico específico (READ ONE)
GET http://localhost:8080/topicos/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmb3JvIGh1YiIsInN1YiI6ImFkcmlhbmFAZW1haWwuY29tIiwiaWQiOjEsImV4cCI6MTc3MTcxODE0OH0.zX9pF0mSo6JcoozK7v9lwGRoYj1DTlXbFXWYq6VliWs


### 4. Actualizar un tópico (UPDATE)
PUT http://localhost:8080/topicos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmb3JvIGh1YiIsInN1YiI6ImFkcmlhbmFAZW1haWwuY29tIiwiaWQiOjEsImV4cCI6MTc3MTcxODE0OH0.zX9pF0mSo6JcoozK7v9lwGRoYj1DTlXbFXWYq6VliWs

Content-Type: application/json

{
  "id": 1,
  "titulo": "Duda resuelta sobre DELETE",
  "mensaje": "¡Ya logré hacer que funcione el borrado!"
}

### 5. Eliminar un tópico (DELETE)
DELETE http://localhost:8080/topicos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmb3JvIGh1YiIsInN1YiI6ImFkcmlhbmFAZW1haWwuY29tIiwiaWQiOjEsImV4cCI6MTc3MTcxODE0OH0.zX9pF0mSo6JcoozK7v9lwGRoYj1DTlXbFXWYq6VliWs
